name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build --if-present


      - name: Push
        env:
          GITHUB_USER: "skonb-github-actions-build"
          GITHUB_EMAIL: "w0rkingc4t0708@gmail.com"
        run: |
            git config --local user.name "${GITHUB_USER}"
            git config --local user.email "${GITHUB_EMAIL}"
            git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
            git add docs
            git commit -m "auto rebuilding site"
            git push origin main